
#line 3 "imyparsf.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* begin standard C++ headers. */

/* flex integer type definitions */

/* Prefer C99 integer types if available. */
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
/* Include <inttypes.h> and not <stdint.h> because Solaris 2.6 has the former
 * and not the latter.
 */
#include <inttypes.h>
# define YYFLEX_USE_STDINT
#else
# if defined(_MSC_VER) && _MSC_VER >= 1600
/* Visual C++ 2010 does not define __STDC_VERSION__ and has <stdint.h> but not
 * <inttypes.h>.
 */
#include <stdint.h>
#  define YYFLEX_USE_STDINT
# endif
#endif
#ifdef YYFLEX_USE_STDINT
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef unsigned char flex_uint8_t;
typedef short int flex_int16_t;
typedef unsigned short int flex_uint16_t;
# ifdef __STDC__
typedef signed char flex_int8_t;
/* ISO C only requires at least 16 bits for int. */
#include <limits.h>
#  if UINT_MAX >= 4294967295
#   define YYFLEX_INT32_DEFINED
typedef int flex_int32_t;
typedef unsigned int flex_uint32_t;
#  endif
# else
typedef char flex_int8_t;
# endif
# ifndef YYFLEX_INT32_DEFINED
typedef long int flex_int32_t;
typedef unsigned long int flex_uint32_t;
# endif
#endif

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[198] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   41,   39,   39,   39,
       38,   38,   38,   38,   38,   38,   38,   38,   35,   20,
       19,   19,   35,   35,   17,   35,   35,   35,   35,   35,
       35,   36,   34,   33,   33,   36,   36,   31,   36,   36,
       36,   36,   36,   36,   36,   36,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   18,    0,    0,    0,   14,
        9,    0,    0,   12,   15,   16,    0,   32,    0,    0,
       26,   29,   21,    0,    0,   24,   27,   28,    0,   30,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   11,

       10,    9,    0,    0,   12,    0,   23,   22,   21,    0,
        0,   24,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   11,   10,    0,    0,    0,   23,   22,    0,
        0,    0,    0,    5,    0,    0,    0,    4,    0,    0,
        0,    0,    0,   13,    0,    0,    0,   25,    0,    0,
        5,    0,    0,    0,    4,    0,    0,    0,    0,   13,
       13,    0,   13,    0,   25,   25,    0,   25,    0,    0,
        3,    8,    6,    0,    0,   13,   13,   25,   25,    0,
        0,    3,    6,    2,    7,    0,    0,    2,    7,    0,
        0,    0,   37,    0,    1,    1,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    6,    7,    6,    6,    8,    6,    9,
       10,   11,   12,    6,   12,   13,    6,   14,   15,   15,
       15,   15,   15,   14,   14,   14,   16,   17,   13,    6,
        6,    6,    6,   18,   19,   20,   21,   22,   23,   24,
       25,    6,   26,    6,   27,   28,   29,   30,   31,    6,
        6,   32,   33,   34,   35,   36,    6,    6,   37,    6,
        6,    6,    6,    6,    6,    6,   38,   39,   40,   41,

       42,   43,   44,    6,   45,    6,   46,   47,   48,   49,
       50,    6,    6,   51,   52,   53,   54,   55,    6,    6,
       56,    6,    6,    6,    6,    6,    6,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    2,    3,    4,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[212] =
    {   0,
        0,    4,    0,   42,   97,    0,  154,    0,  460,  459,
      205,    0,    0,    0,    0,    1,  468,  471,  471,    0,
      471,    2,    0,    0,    3,    0,    0,    4,  471,  471,
        6,    8,    0,    0,  471,    0,  452,    1,    5,  451,
      205,  471,  471,    0,  471,    0,    0,  471,    3,   44,
      448,   14,    9,  443,  239,  441,   23,    2,    0,   31,
       36,   39,   32,   38,   45,  471,   73,  433,  428,  471,
      201,   53,  193,  219,  471,  224,  222,  471,  423,  419,
      471,  243,  249,  242,  242,  254,  471,  254,  252,  471,
      247,  240,  416,  246,  245,  254,  250,  246,  245,  268,

      273,  471,  260,  257,  471,  266,  287,  288,  471,  275,
      272,  471,  286,  280,  415,  285,  293,  291,  410,  291,
      289,  287,  471,  471,  286,  294,  288,  471,  471,  289,
      316,  292,  385,    0,  296,  292,  304,    0,  384,  316,
      325,  325,  326,  471,  327,  328,  329,  471,  332,  328,
        0,  338,  383,  382,    0,  330,  334,  310,  354,  471,
      471,  355,  471,  360,  471,  471,  361,  471,  357,  359,
        0,  471,    0,  218,  352,  471,  471,  471,  471,  366,
      359,    0,    0,    0,    0,  363,  370,    0,    0,  362,
      357,  373,  471,  359,   76,   92,  471,  415,  420,  425,

      217,   81,  430,    8,    2,  435,  440,  445,  450,  455,
      460
    } ;

static const flex_int16_t yy_def[212] =
    {   0,
      198,  198,  199,  199,  197,    5,  197,    7,    7,    7,
        7,   11,   11,   11,   11,   11,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      200,  200,  201,  202,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  203,  197,  204,  205,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  200,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  206,  197,  197,  197,  207,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      206,  197,  197,  197,  207,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      208,  197,  209,  197,  197,  197,  197,  197,  197,  197,
      197,  208,  209,  210,  211,  197,  197,  210,  211,  197,
      197,  197,  197,  197,  197,  197,    0,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197
    } ;

static const flex_int16_t yy_nxt[529] =
    {   0,
       18,   18,  197,   18,   18,   18,   80,   18,   67,   67,
       67,   67,   79,   70,   70,   71,   81,   81,   62,   72,
       92,   93,   57,   20,   58,   61,   64,   73,   83,   59,
       60,   85,   84,   63,   65,   42,   42,   62,   72,   92,
       93,   57,   20,   58,   61,   64,   73,   91,   59,   60,
       85,   84,   63,   65,   42,   42,   18,   82,   82,   82,
       18,   22,   94,   95,   23,   24,   91,   96,   97,   98,
       25,   26,   99,  103,   27,   67,   67,   28,  196,  196,
       22,   94,   95,   23,   24,   69,   96,   97,   98,   25,
       26,   99,  103,   27,  196,  196,   28,   29,   30,   31,

       32,   30,   29,   33,   34,   35,   29,   36,   29,   29,
       29,   29,   29,   29,   29,   37,   38,   37,   37,   37,
       37,   37,   29,   29,   39,   29,   29,   29,   40,   29,
       29,   29,   41,   29,   37,   38,   37,   37,   37,   37,
       37,   29,   29,   39,   29,   29,   29,   40,   29,   29,
       29,   41,   29,   29,   42,   43,   44,   45,   43,   42,
       46,   47,   42,   48,   49,   42,   42,   42,   42,   42,
       42,   50,   51,   52,   51,   51,   51,   51,   51,   42,
       42,   53,   42,   42,   42,   54,   42,   42,   42,   55,
       42,   51,   52,   51,   51,   51,   51,   51,   42,   42,

       53,   42,   42,   42,   54,   42,   42,   42,   55,   42,
       42,   42,   42,  102,  104,   42,   75,  102,   76,   76,
       76,   68,   42,   42,   42,   42,   42,   42,   42,   42,
       77,  105,   42,  104,  184,  105,   42,   76,   76,   76,
       56,  106,   42,   42,   42,   42,   42,   42,   42,   77,
       87,   42,   88,   88,   88,   42,   82,   82,   82,   56,
      106,  109,  110,  111,   89,  109,  112,   88,   88,   88,
      112,  113,  114,  115,  117,  118,  119,  120,  121,  122,
      123,  110,  111,   89,  123,  124,  125,  126,  127,  124,
      113,  114,  115,  117,  118,  119,  120,  121,  122,  128,

      129,  130,  131,  128,  129,  125,  126,  127,  132,  133,
      135,  136,  137,  139,  140,  141,  142,  143,  145,  146,
      130,  131,  149,  144,  152,  153,  175,  132,  133,  135,
      136,  137,  139,  140,  141,  142,  143,  145,  146,  147,
      154,  149,  144,  152,  153,  148,  157,  158,  159,  161,
      162,  164,  166,  169,  160,  167,  163,  165,  147,  154,
      170,  168,  173,  174,  148,  157,  158,  159,  161,  162,
      164,  166,  169,  160,  167,  163,  165,  176,  177,  170,
      168,  173,  174,  178,  179,  180,  181,  185,  186,  187,
      190,  191,  192,  193,  194,  195,  176,  177,  172,  171,

      156,  150,  178,  179,  180,  181,  185,  186,  187,  190,
      191,  192,  193,  194,  195,   19,   19,   19,   19,   19,
       21,   21,   21,   21,   21,   66,  138,   66,   66,   66,
       78,  134,  116,  108,   78,  151,  151,  107,  151,  151,
      155,  155,  101,  155,  155,  182,  182,  100,  182,  182,
      183,  183,   90,  183,  183,  188,  188,   86,  188,  188,
      189,  189,   83,  189,  189,   74,   71,  197,   42,   42,
       17,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197
    } ;

static const flex_int16_t yy_chk[529] =
    {   0,
        1,    1,    0,    1,    2,    2,  205,    2,   31,   31,
       32,   32,  204,   36,   36,   38,   49,   49,   26,   38,
       58,   59,   20,    2,   22,   25,   28,   39,   52,   23,
       24,   53,   52,   27,   28,   15,   16,   26,   38,   58,
       59,   20,    2,   22,   25,   28,   39,   57,   23,   24,
       53,   52,   27,   28,   15,   16,    1,   50,   50,   50,
        2,    4,   60,   61,    4,    4,   57,   62,   63,   64,
        4,    4,   65,   72,    4,   67,   67,    4,  195,  195,
        4,   60,   61,    4,    4,  202,   62,   63,   64,    4,
        4,   65,   72,    4,  196,  196,    4,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,   11,   11,   71,   73,   11,   41,   71,   41,   41,
       41,  201,   11,   11,   11,   11,   11,   11,   11,   11,
       41,   74,   11,   73,  174,   74,   11,   76,   76,   76,
       11,   77,   11,   11,   11,   11,   11,   11,   11,   41,
       55,   11,   55,   55,   55,   11,   82,   82,   82,   11,
       77,   83,   84,   85,   55,   83,   86,   88,   88,   88,
       86,   89,   91,   92,   94,   95,   96,   97,   98,   99,
      100,   84,   85,   55,  100,  101,  103,  104,  106,  101,
       89,   91,   92,   94,   95,   96,   97,   98,   99,  107,

      108,  110,  111,  107,  108,  103,  104,  106,  113,  114,
      116,  117,  118,  120,  121,  122,  125,  126,  127,  130,
      110,  111,  132,  126,  135,  136,  158,  113,  114,  116,
      117,  118,  120,  121,  122,  125,  126,  127,  130,  131,
      137,  132,  126,  135,  136,  131,  140,  141,  142,  143,
      145,  146,  147,  150,  142,  149,  145,  146,  131,  137,
      152,  149,  156,  157,  131,  140,  141,  142,  143,  145,
      146,  147,  150,  142,  149,  145,  146,  159,  162,  152,
      149,  156,  157,  164,  167,  169,  170,  175,  180,  181,
      186,  187,  190,  191,  192,  194,  159,  162,  154,  153,

      139,  133,  164,  167,  169,  170,  175,  180,  181,  186,
      187,  190,  191,  192,  194,  198,  198,  198,  198,  198,
      199,  199,  199,  199,  199,  200,  119,  200,  200,  200,
      203,  115,   93,   80,  203,  206,  206,   79,  206,  206,
      207,  207,   69,  207,  207,  208,  208,   68,  208,  208,
      209,  209,   56,  209,  209,  210,  210,   54,  210,  210,
      211,  211,   51,  211,  211,   40,   37,   17,   10,    9,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[41] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "imyparsf.l"
#line 2 "imyparsf.l"
/*
 * IMYplay - A program for playing iMelody ringtones (IMY files).
 *	-- melody parsing file using (f)lex.
 *
 * Copyright (C) 2009-2023 Bogdan Drozdowski, bogdro (at) users.sourceforge.net
 * License: GNU General Public License, v3+
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include "imyp_cfg.h"

#include <stdio.h>

#ifdef HAVE_STRING_H
# if ((!defined STDC_HEADERS) || (!STDC_HEADERS)) && (defined HAVE_MEMORY_H)
#  include <memory.h>
# endif
# include <string.h>
#endif

#ifdef HAVE_LIBINTL_H
# include <libintl.h>	/* translation stuff */
#endif

#ifdef HAVE_LOCALE_H
# include <locale.h>
#endif

#include "imyplay.h"
#include "imyp_sig.h"
#include "imypwrap.h"
#include "imyparse.h"
#include "iparsers.h"

static unsigned short int buf16[IMYP_SAMPBUFSIZE];

static int volume;
static int style;
static int bpm;
static int octave;

static int pos;
static int repeat_count;
static int repeat_pos;

static int scanf_res;
static int play_result;
static int note_duration;
static imyp_backend_t * curr;

#define ECHO do { imyp_put_text (yytext, curr); } while (0)

#ifdef TEST_COMPILE
# undef IMYP_ANSIC
# if TEST_COMPILE > 1
#  undef HAVE_MALLOC
# endif
#endif

/* ======================================================================== */

#ifndef IMYP_ANSIC
static int imyp_get_duration IMYP_PARAMS ((const char * const note_buffer, int current_bpm));
#endif

/**
 * Gets the duration of the note pointed to by buf.
 * \param note_buffer A character buffer with the note's description.
 * \param current_bpm The current BPM value.
 * \return a duration for the first note in the buffer, in milliseconds.
 */
static int
#ifdef IMYP_ANSIC
IMYP_ATTR((nonnull))
#endif
imyp_get_duration (
#ifdef IMYP_ANSIC
	const char * const note_buffer,
	int current_bpm)
#else
	note_buffer, current_bpm)
	const char * const note_buffer;
	int current_bpm;
#endif
{
	float duration = 0.0f;
	unsigned int dur_shift = 0;

	if ( note_buffer == NULL )
	{
		return 0;
	}
	scanf_res = sscanf (note_buffer+1, "%u", &dur_shift);
	if ( scanf_res != 1 )
	{
		return 0;
	}
	if ( dur_shift == 0 )
	{
		duration = 1000.0f;
	}
	else
	{
		duration = 1000.0f/(float)(1<<dur_shift);
	}
	if ( note_buffer[2] == '.' )
	{
		duration *= 1.5f;
	}
	else if ( note_buffer[2] == ':' )
	{
		duration *= 2;
	}
	else if ( note_buffer[2] == ';' )
	{
		duration = (duration*2.0f)/3.0f;
	}
	if ( current_bpm == 0 )
	{
		current_bpm = IMYP_DEF_BPM;
	}
	return (int)IMYP_ROUND (duration * ((1.0f*IMYP_DEF_BPM)/(1.0f*(double)current_bpm)));
}

/* ======================================================================== */

#ifndef IMYP_ANSIC
static void imyp_play_current_note IMYP_PARAMS ((const char melody[],
	int * const duration, imyp_backend_t * const curr_lib,
	int * const play_res, const int is_sharp,
	const int is_flat, const int current_bpm));
#endif

/**
 * Play the given note. Also resets the sharp and flat flags.
 * \param[in] melody The note string to play.
 * \param[out] duration The duration of the note.
 * \param[in] curr_lib The current output backend.
 * \param[out] play_res The result of playing the note.
 * \param[in] is_sharp Non-zero if the note is sharp.
 * \param[in] is_flat Non-zero if the note is flat.
 * \param[in] current_bpm The current BPM value.
 */
static void
#ifdef IMYP_ANSIC
IMYP_ATTR((nonnull))
#endif
imyp_play_current_note (
#ifdef IMYP_ANSIC
	const char melody[], int * const duration,
	imyp_backend_t * const curr_lib, int * const play_res,
	const int is_sharp, const int is_flat, const int current_bpm)
#else
	melody, duration, curr_lib, play_res, is_sharp, is_flat, current_bpm)
	const char melody[];
	int * const duration;
	imyp_backend_t * const curr_lib;
	int * const play_res;
	const int is_sharp;
	const int is_flat;
	const int current_bpm;
#endif
{
	int note_index = 0;

	if ( (duration == NULL) || (curr_lib == NULL)
		|| (play_res == NULL) || (duration == NULL) )
	{
		return;
	}
	if ( curr_lib->imyp_curr_lib == IMYP_CURR_NONE )
	{
		return;
	}

	if ( IMYP_TOUPPER (melody[0]) == 'C' )
	{
		note_index = 0;
	}
	else if ( IMYP_TOUPPER (melody[0]) == 'D' )
	{
		note_index = 2;
	}
	else if ( IMYP_TOUPPER (melody[0]) == 'E' )
	{
		note_index = 4;
	}
	else if ( IMYP_TOUPPER (melody[0]) == 'F' )
	{
		note_index = 5;
	}
	else if ( IMYP_TOUPPER (melody[0]) == 'G' )
	{
		note_index = 7;
	}
	else if ( IMYP_TOUPPER (melody[0]) == 'A' )
	{
		note_index = 9;
	}
	else if ( IMYP_TOUPPER (melody[0]) == 'B' )
	{
		note_index = 11;
	}

	*duration = imyp_get_duration (melody, current_bpm);
	if ( (is_flat != 0) && (note_index == 0) && (octave != 0) )
	{
		/* flat 'C' note, but not the first 'C' note */
		*play_res = imyp_play_tune (imyp_notes[octave-1][IMYP_NOTES_PER_OCTAVE-1],
			volume, *duration,
			buf16, IMYP_SAMPBUFSIZE, curr_lib);
		if ( (*play_res != 0) && (imyp_sig_recvd == 0) )
		{
			printf ("%s\n", _(err_play_tune));
		}
	}
	else if ( (is_flat != 0) && (note_index != 0) )
	{
		/* flat note and not a 'C' note */
		*play_res = imyp_play_tune (imyp_notes[octave][note_index-1],
			volume, *duration,
			buf16, IMYP_SAMPBUFSIZE, curr_lib);
		if ( (*play_res != 0) && (imyp_sig_recvd == 0) )
		{
			printf ("%s\n", _(err_play_tune));
		}
	}
	else if ( (is_sharp != 0) && (note_index == IMYP_NOTES_PER_OCTAVE-1)
		&& (octave < IMYP_OCTAVES) )
	{
		/* sharp 'B' note and not the last 'B' note */
		*play_res = imyp_play_tune (imyp_notes[octave+1][0],
			volume, *duration,
			buf16, IMYP_SAMPBUFSIZE, curr_lib);
		if ( (*play_res != 0) && (imyp_sig_recvd == 0) )
		{
			printf ("%s\n", _(err_play_tune));
		}
	}
	else if ( (is_sharp != 0) && (note_index != IMYP_NOTES_PER_OCTAVE-1) )
	{
		/* sharp note and not a 'B' note */
		*play_res = imyp_play_tune (imyp_notes[octave][note_index+1],
			volume, *duration,
			buf16, IMYP_SAMPBUFSIZE, curr_lib);
		if ( (*play_res != 0) && (imyp_sig_recvd == 0) )
		{
			printf ("%s\n", _(err_play_tune));
		}
	}
	else
	{
		/* Normal note. We also get here on the first 'C', when
		   the flat flag is on or on the last 'B' when the
		   sharp flag is on. */
		*play_res = imyp_play_tune (imyp_notes[octave][note_index],
			volume, *duration,
			buf16, IMYP_SAMPBUFSIZE, curr_lib);
		if ( (*play_res != 0) && (imyp_sig_recvd == 0) )
		{
			printf ("%s\n", _(err_play_tune));
		}
	}
	imyp_pause (imyp_get_rest_time (*duration, style), curr_lib, 1, buf16, IMYP_SAMPBUFSIZE);
}

/* ======================================================================== */

#ifndef IMYP_ANSIC
static void imyp_make_pause IMYP_PARAMS ((const char melody[],
	imyp_backend_t * const curr_lib, const int current_bpm));
#endif

/**
 * Make a pause in the melody.
 * \param[in] melody The pause string.
 * \param[in] curr_lib The current output backend.
 * \param[in] current_bpm The current BPM value.
 */
static void
#ifdef IMYP_ANSIC
IMYP_ATTR((nonnull))
#endif
imyp_make_pause (
#ifdef IMYP_ANSIC
	const char melody[], imyp_backend_t * const curr_lib, const int current_bpm)
#else
	melody, curr_lib, current_bpm)
	const char melody[];
	imyp_backend_t * const curr_lib;
	const int current_bpm;
#endif
{
	if ( (melody == NULL) || (curr_lib == NULL) || (imyp_sig_recvd != 0) )
	{
		return;
	}
	if ( curr_lib->imyp_curr_lib == IMYP_CURR_NONE )
	{
		return;
	}
	imyp_pause (imyp_get_duration (melody, current_bpm), curr_lib, 0, buf16, IMYP_SAMPBUFSIZE);
}

#line 956 "imyparsf.c"
/* ======================================================================== */
/*%option fast - disables 8-bit, not needed */
#line 327 "imyparsf.l"
 /*%option outfile="imyparsf.c" -- is taken care of by autoconf/automake */
 /* portability, recommended by autoconf: */







#line 969 "imyparsf.c"

#define INITIAL 0
#define IN_IMELODY 1
#define IN_MELODY_LINE 2
#define IN_REPEAT_BLOCK 3
#define IN_REPEAT_BLOCK_PASS 4
#define REPEAT_BLOCK_VOL 5
#define REPEAT_BLOCK_VOL_PASS 6
#define REPEAT_BLOCK_END 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 361 "imyparsf.l"


#line 1197 "imyparsf.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 198 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 197 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_more_len); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 363 "imyparsf.l"
{

	BEGIN (IN_IMELODY);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 368 "imyparsf.l"
ECHO;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 370 "imyparsf.l"
ECHO;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 372 "imyparsf.l"
ECHO;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 374 "imyparsf.l"
{

	ECHO;
	/* parse beat */
	scanf_res = sscanf (yytext+5 /* "BEAT:" */, "%d", &bpm);
	if ( scanf_res != 1 )
	{
		printf ("%s: %s.\n", _(err_parse_beat), yytext+5);
		bpm = 120;
	}
	if ( (bpm < 25) || (bpm > 900) )
	{
		bpm = 120;
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 394 "imyparsf.l"
{

	ECHO;
	/* parse style */
	scanf_res = sscanf (yytext+7 /* "STYLE:S" */, "%d", &style);
	if ( scanf_res != 1 )
	{
		printf ("%s: %s.\n", _(err_parse_style), yytext+7);
		style = 0;
	}
	if ( (style < 0) || (style > 2) )
	{
		style = 0;
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 414 "imyparsf.l"
{

	ECHO;
	/* parse volume */
	scanf_res = sscanf (yytext+8 /* VOLUME:V */, "%d", &volume);
	if ( scanf_res != 1 )
	{
		printf ("%s: %s.\n", _(err_parse_vol), yytext+8);
		volume = 7;
	}
	if ( volume < 0 )
	{
		volume = 0;
	}
	else if ( volume > IMYP_MAX_IMY_VOLUME )
	{
		volume = IMYP_MAX_IMY_VOLUME;
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
/* don't use "^MELODY:{FULL_MELODY} here, because we want to catch unknown tokens
	ourselves and play the rest of the melody anyway. */
case 8:
YY_RULE_SETUP
#line 440 "imyparsf.l"
{

	pos = 0;
	BEGIN (IN_MELODY_LINE);
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 450 "imyparsf.l"
{

	imyp_play_current_note (yytext, &note_duration, curr, &play_result, 0, 0, bpm);
	/* update the line position to display the position of unknown tokens */
	pos += yyleng;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 461 "imyparsf.l"
{

	imyp_play_current_note (yytext+1 /* skip the '&' */, &note_duration,
		curr, &play_result, 0, 1, bpm);
	/* update the line position to display the position of unknown tokens */
	pos += yyleng;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 473 "imyparsf.l"
{

	imyp_play_current_note (yytext+1 /* skip the '#' */, &note_duration,
		curr, &play_result, 1, 0, bpm);
	/* update the line position to display the position of unknown tokens */
	pos += yyleng;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 485 "imyparsf.l"
{

	imyp_make_pause (yytext, curr, bpm);
	/* update the line position to display the position of unknown tokens */
	pos += yyleng;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 496 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	pos += yyleng;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 506 "imyparsf.l"
{

	scanf_res = sscanf (yytext+1, "%d", &octave);
	if ( scanf_res == 1 )
	{
		if ( octave < 0 )
		{
			octave = 0;
		}
		else if ( octave > 8 )
		{
			octave = 8;
		}
	}
	else
	{
		printf ("%s: '%c' (0x%x) %s %d:%d\n",
			_(err_unkn_token),
			*yytext,
			(unsigned int)*yytext,
			_(err_at_pos),
			yylineno,
			pos+1);
	}
	/* update the line position to display the position of unknown tokens */
	pos += yyleng;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 538 "imyparsf.l"
{

	if ( *(yytext+1) == '-' )
	{
		volume--;
	}
	else if ( *(yytext+1) == '+' )
	{
		volume++;
	}
	if ( volume < 0 )
	{
		volume = 0;
	}
	else if ( volume > IMYP_MAX_IMY_VOLUME )
	{
		volume = IMYP_MAX_IMY_VOLUME;
	}
	/* update the line position to display the position of unknown tokens */
	pos += yyleng;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 564 "imyparsf.l"
{

	scanf_res = sscanf (yytext+1, "%d", &volume);
	if ( scanf_res != 1 )
	{
		printf ("%s: %s.\n", _(err_parse_vol), yytext+8);
	}
	if ( volume < 0 )
	{
		volume = 0;
	}
	else if ( volume > IMYP_MAX_IMY_VOLUME )
	{
		volume = IMYP_MAX_IMY_VOLUME;
	}
	/* update the line position to display the position of unknown tokens */
	pos += yyleng;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 587 "imyparsf.l"
{

	pos += yyleng;
	BEGIN (IN_REPEAT_BLOCK);
	/* initialize repeat block variables: */
	repeat_count = -2;
	repeat_pos = pos;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 600 "imyparsf.l"
{

	/* a newline NOT followed by whitespace means the end of the melody line. */
	BEGIN (IN_IMELODY);
	/* return everything to the stream, so we can catch the line again. */
	yyless (0);
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
/* eat up newlines inside the melody and reset the line position: */
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 613 "imyparsf.l"
{

	pos = 0;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
/* eat up whitespace inside the melody, but update the position: */
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 623 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	pos += yyleng;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 633 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( YY_START == IN_REPEAT_BLOCK_PASS /*repeat_count != -2*/ )
	{
		/* perform any action here, where we know that the block has been fully parsed */
		imyp_play_current_note (yytext + yyleng-2, &note_duration, curr,
			&play_result, 0, 0, bpm);
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 652 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( YY_START == IN_REPEAT_BLOCK_PASS /*repeat_count != -2*/ )
	{
		/* perform any action here, where we know that the block has been fully parsed */
		imyp_play_current_note (yytext + yyleng-3 + 1 /* skip the '&' */,
			&note_duration, curr, &play_result, 0, 0, bpm);
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 671 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( YY_START == IN_REPEAT_BLOCK_PASS /*repeat_count != -2*/ )
	{
		/* perform any action here, where we know that the block has been fully parsed */
		imyp_play_current_note (yytext + yyleng-3 + 1 /* skip the '#' */,
			&note_duration, curr, &play_result, 0, 0, bpm);
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 690 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( YY_START == IN_REPEAT_BLOCK_PASS /*repeat_count != -2*/ )
	{
		/* perform any action here, where we know that the block has been fully parsed */
		imyp_make_pause (yytext, curr, bpm);
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 708 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( YY_START == IN_REPEAT_BLOCK_PASS /*repeat_count != -2*/ )
	{
		/* perform any action here, where we know that the block has been fully parsed */
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 725 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( YY_START == IN_REPEAT_BLOCK_PASS /*repeat_count != -2*/ )
	{
		/* perform any action here, where we know that the block has been fully parsed */
		scanf_res = sscanf (yytext + yyleng-2+1, "%d", &octave);
		if ( scanf_res == 1 )
		{
			if ( octave < 0 )
			{
				octave = 0;
			}
			else if ( octave > 8 )
			{
				octave = 8;
			}
		}
		else
		{
			printf ("%s: '%c' (0x%x) %s %d:%d\n",
				_(err_unkn_token),
				*yytext,
				(unsigned int)*yytext,
				_(err_at_pos),
				yylineno,
				repeat_pos+1);
		}
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 764 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( YY_START == IN_REPEAT_BLOCK_PASS /*repeat_count != -2*/ )
	{
		/* perform any action here, where we know that the block has been fully parsed */
		if ( *(yytext+yyleng-2+1) == '-' )
		{
			volume--;
		}
		else if ( *(yytext+yyleng-2+1) == '+' )
		{
			volume++;
		}
		if ( volume < 0 )
		{
			volume = 0;
		}
		else if ( volume > IMYP_MAX_IMY_VOLUME )
		{
			volume = IMYP_MAX_IMY_VOLUME;
		}
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 797 "imyparsf.l"
{

	char * vol_ptr = NULL;
	char * last_v = strrchr (yytext, 'v');
	char * last_V = strrchr (yytext, 'V');
	if ( (last_v != NULL) && (last_V != NULL) )
	{
		vol_ptr = (last_v > last_V)? last_v : last_V;
	}
	else if ( last_v != NULL )
	{
		vol_ptr = last_v;
	}
	else if ( last_V != NULL )
	{
		vol_ptr = last_V;
	}
	/*printf ("Got new volume (value) in repeat block: '%s'\n", yytext);*/
	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( YY_START == IN_REPEAT_BLOCK_PASS /*repeat_count != -2*/ )
	{
		/* perform any action here, where we know that the block has been fully parsed */
		if ( vol_ptr != NULL )
		{
			scanf_res = sscanf (vol_ptr+1, "%d", &volume);
			if ( scanf_res != 1 )
			{
				printf ("%s: %s.\n", _(err_parse_vol), yytext+8);
			}
			if ( volume < 0 )
			{
				volume = 0;
			}
			else if ( volume > IMYP_MAX_IMY_VOLUME )
			{
				volume = IMYP_MAX_IMY_VOLUME;
			}
		}
		else
		{
			printf ("%s: '%c' (0x%x) %s %d:%d\n",
				_(err_unkn_token),
				*yytext,
				(unsigned int)*yytext,
				_(err_at_pos),
				yylineno,
				repeat_pos+1);
		}
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 856 "imyparsf.l"
{

	if ( YY_START == IN_REPEAT_BLOCK /*repeat_count == -2*/ )
	{
		if ( sscanf (strchr (yytext, '@')+1, "%d", &repeat_count) == 1 )
		{
			if ( repeat_count == 0 ) repeat_count = -1;
		}
		else
		{
			printf ("%s: '%c' (0x%x) %s %d:%d\n",
				_(err_unkn_token),
				*yytext,
				(unsigned int)*yytext,
				_(err_at_pos),
				yylineno,
				repeat_pos+1);
		}
		/* perform initial volume setting */
		BEGIN (REPEAT_BLOCK_VOL);
	}
	else
	{
		/* do NOT perform any volume setting for the whole block */
		BEGIN (REPEAT_BLOCK_VOL_PASS);
	}
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 891 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( YY_START == REPEAT_BLOCK_VOL /*repeat_count != -2*/ )
	{
		/* perform any action here, where we know that the block has been fully parsed */
		if ( *(yytext+yyleng-2+1) == '-' )
		{
			volume--;
		}
		else if ( *(yytext+yyleng-2+1) == '+' )
		{
			volume++;
		}
		if ( volume < 0 )
		{
			volume = 0;
		}
		else if ( volume > IMYP_MAX_IMY_VOLUME )
		{
			volume = IMYP_MAX_IMY_VOLUME;
		}
	}
	BEGIN (REPEAT_BLOCK_END);
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 925 "imyparsf.l"
{

	if ( repeat_count == -1 )
	{
		/* infinite repeat: return everything to the stream, so we can catch the line again. */
		yyless (0);
		BEGIN (IN_REPEAT_BLOCK_PASS);
	}
	else
	{
		repeat_count--;
		if ( repeat_count > 0 )
		{
			/* return everything to the stream, so we can catch the line again. */
			yyless (0);
			BEGIN (IN_REPEAT_BLOCK_PASS);
		}
		else
		{
			repeat_count = -2;
			/* back to "normal" melody mode. */
			BEGIN (IN_MELODY_LINE);
			repeat_pos = 0;
		}
	}
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 956 "imyparsf.l"
{

	/* a newline NOT followed by whitespace means the end of the melody line. */
	BEGIN (IN_IMELODY);
	/* return everything to the stream, so we can catch the line again. */
	yyless (0);
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
/* eat up newlines inside the melody and reset the line position: */
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 969 "imyparsf.l"
{

	pos = 0;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
/* eat up whitespace inside the melody, but update the position: */
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 982 "imyparsf.l"
{

	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
/* anything not processed up to here is an unknown token */
case 35:
YY_RULE_SETUP
#line 996 "imyparsf.l"
{

	printf ("%s: '%c' (0x%x) %s %d:%d\n",
		_(err_unkn_token),
		*yytext,
		(unsigned int)*yytext,
		_(err_at_pos),
		yylineno,
		pos+1);
	/* update the line position to display the position of unknown tokens */
	pos += yyleng;
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
/* anything not processed up to here is an unknown token */
case 36:
YY_RULE_SETUP
#line 1014 "imyparsf.l"
{

	printf ("%s: '%c' (0x%x) %s %d:%d\n",
		_(err_unkn_token),
		*yytext,
		(unsigned int)*yytext,
		_(err_at_pos),
		yylineno,
		repeat_pos+1);
	/* update the line position to display the position of unknown tokens */
	repeat_pos = pos + yyleng;
	/* in a repeat block, collect all the elements to repeat and return to them
	   after looking throuhg the whole repeat block. */
	yymore ();
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 1034 "imyparsf.l"
{

	BEGIN (INITIAL);
	ECHO;
	/* print a newline no matter if it was present in the file, so we can use just one pattern. */
	printf ("\n");
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 1046 "imyparsf.l"
{

	ECHO; /* echo unknown lines inside the melody block */
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 1055 "imyparsf.l"
{
/* NOTE: using just ".|\x00" is NOT enough */

	fflush(stdout);
	/* eat up everything before "BEGIN:IMELODY" or after "END:IMELODY" */
	if ( imyp_sig_recvd != 0 )
	{
		return -1;
	}
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 1066 "imyparsf.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 2101 "imyparsf.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_IMELODY):
case YY_STATE_EOF(IN_MELODY_LINE):
case YY_STATE_EOF(IN_REPEAT_BLOCK):
case YY_STATE_EOF(IN_REPEAT_BLOCK_PASS):
case YY_STATE_EOF(REPEAT_BLOCK_VOL):
case YY_STATE_EOF(REPEAT_BLOCK_VOL_PASS):
case YY_STATE_EOF(REPEAT_BLOCK_END):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 198 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 198 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 197);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 1066 "imyparsf.l"


/* ======================================================================== */

/**
 * Plays the given IMY file.
 * \param file_name The name of the file to play.
 * \return 0 on success
 */
int
#ifdef IMYP_ANSIC
IMYP_ATTR((nonnull))
#endif
imyp_play_file (
#ifdef IMYP_ANSIC
	const char * const file_name, imyp_backend_t * const curr_lib)
#else
	file_name, curr_lib)
	const char * const file_name;
	imyp_backend_t * const curr_lib;
#endif
{
	FILE * imy;
	if ( (file_name == NULL) || (curr_lib == NULL) )
	{
		return -100;
	}

	/* re-initialize the parser for each file: */
	volume = 7;
	style = 0;
	bpm = IMYP_DEF_BPM;
	octave = 4;

	pos = 0;
	repeat_count = 0;
	repeat_pos = 0;

	note_duration = 0;

	if ( curr_lib->imyp_curr_lib != IMYP_CURR_NONE )
	{
		imy = fopen (file_name, "r");
		if ( imy != NULL )
		{
			curr = curr_lib;
			yyin = imy;
			yylex ();
			/* file parsing done, free all memory: */
			yylex_destroy ();
			fclose (imy);
			return 0;
		}
		else
		{
			printf ("%s %s.\n", _(err_file_open), file_name);
			return -2;
		}
	}
	return -1;
}

